export const APP_KYC = {
    heading : 'Verify Your Account',
    subHeading : 'Get Priority customer service by verifying KYC',
    kycTerms  : [
        "Note: Your name on the PAN card and in UPI/Bank should match.",
        "KYC verification of PAN usually happens within 24 Hrs.",
        "PAN card submitted is used only for verification.",
    ],
    panSectionMeta : {
        "PAN.Heading": "Verify PAN",
        "PAN.View.Image.Upload.Message": 'uploading image',
        "PAN.View.Extract.Details.Message": 'Getting your PAN details',
        "PAN.View.Submit.Details.Message": 'Submitting PAN Details',
        "PAN.View.Upload.PAN.Heading": "Upload PAN",
        "PAN.View.Upload.PAN.Message": "We support PNG/JPG and PDF file formats and request you to keep size less than 5 MB",
        "PAN.View.Submit.Text": "VERIFY PAN",
        "PAN.View.Retry.Submit.Text": 'RETRY VERIFYING PAN',
        "PAN.View.PAN.Name.Label": "PAN holder’s name",
        "PAN.View.PAN.Number.Label": "PAN number",
        "PAN.View.DOB.Label": "Date of birth",
        "PAN.View.Guideline.Text": "See Guidelines",
        "PAN.View.Upload.Image.Label": "Upload PAN image",
        "PAN.View.Verify.Details": "Please make sure PAN details are correct before submitting for verification",
        "KYC.Rejected.Title": "Rejected: PAN image & PAN number provided by you did not match.",
        "KYC.Processing.Title": "Verification processing...",
        "KYC.Pending.Title": "Not verified yet",
        "KYC.Verified.Title": "Verified",
        "KYC.Image.Rejected.Title": "Re-Upload PAN image",
        "KYC.Image.Processing.Title": "Uploading pan...",
        "KYC.Image.Pending.Title": "Tap to upload image",
        "KYC.Image.Verified.Title": "PAN Card",
        "KYC.Image.Error.Title": "Uploading PAN failed! Please Retry Again!",
    },
    bankMeta : {
        "Bank.Heading": "Verify UPI / Bank Account",
        "Bank.View.IFSC.Error": "Please enter valid IFSC Code",
        "Bank.View.Image.Upload.Message": 'uploading image',
        "Bank.View.Verify.Details": "Name on the Bank account should match the name on PAN",
        "Bank.Image.Title": "Cancelled cheques/bank statement/passbook",
        "Bank.Image.Rejected.Title": "Re-Upload image",
        "Bank.Image.Processing.Title": "Uploading image...",
        "Bank.Image.Pending.Title": "Tap to upload image",
        "Bank.Image.Verified.Title": "Bank Document",
        "Bank.Image.Error.Title": "Uploading image failed! Please Retry Again!",
        "KYC.Not.Submitted.Error": 'PAN details are not submitted',
        "Bank.View.Submit.Details.Message": 'Submitting BANK Details',
        "Upi.View.Submit.Details.Message": 'Submitting UPI Details',
        "Bank.View.Bank.Tab.Text": "Bank Account",
        "Bank.View.Upi.Tab.Text": "UPI",
        "Bank.Rejected.Title": "Rejected: Bank details and PAN details provided by you did not match.",
        "Bank.Processing.Title": "Bank details Verification processing...",
        "Bank.Pending.Title": "Add details to withdraw",
        "Bank.Verified.Title": "Bank details Verified",
        "UPI.Rejected.Title": "Rejected: UPI details and PAN details provided by you did not match.",
        "UPI.Processing.Title": "UPI details Verification processing...",
        "UPI.Pending.Title": "Add details to withdraw",
        "UPI.Verified.Title": "UPI details Verified",
        "Bank.View.Submit.Text": "VERIFY BANK ACCOUNT",
        "Bank.View.Retry.Submit.Text": 'RETRY VERIFYING BANK ACCOUNT',
        "Bank.View.Account.Number.Label": "Account Number",
        "Bank.View.IFSC.Label": "IFSC",
        "Bank.View.Guideline.Text": "See Guidelines",
        "Bank.View.Upload.Image.Label": "Upload Bank document",
        "Bank.View.Upload.Bank.Heading": "Upload Bank document",
        "Bank.View.Upload.Bank.Message": "We support PNG/JPG and PDF file formats and request you to keep size less than 5 MB",
        "Upi.View.Upi.Id.Label": "Enter UPI ID",
        "Upi.View.Submit.Text": "VERIFY UPI",
        "Upi.View.Retry.Submit.Text": 'RETRY VERIFYING UPI',
        "Upi.View.Verify.Details": "Name on the UPI account should match the name on PAN",
    },
    panGuidelinesMeta : {
        heading: "PAN Card Guidelines",
        guidelines: ["1. Please upload the image of the front side of the PAN card.", "2. Please ensure you are uploading PAN card images.", "3. Please ensure name and DOB on the PAN is visible."]
    },
    bankGuidelinesMeta : {
        heading: "Bank Proof Guidelines",
         tabs : [
            {
              name: 'Cheque',
              id: 0,
              guidelines: ["1. You can choose to upload image of canceled cheque for bank proof.","2. A canceled check is a check that has been paid or cleared by the bank it was drawn on after it has been deposited or cashed.","3. Please ensure name on the pan card should match the bank account holder's name on cheque.","4. Please ensure image uploaded is clear and readable."],
            },
            {
              name: 'Passbook',
              id: 1,
              guidelines : ["1. You can choose to upload image of passbook for bank proof.","2. Passbook is book issued by your bank which has a record of all transactions done with the bank.", "3. Please ensure name on the pan card should match the bank account holder's name on passbook.", "4. Please ensure image uploaded is clear and readable."],
            },
            {
              name: 'Statement',
              id: 2,
              guidelines : ["1. You can choose to upload image of statement for bank proof.","2. A bank statement is the summary of all your transactions done with the bank for given period.","3. Please ensure name on the pan card should match the bank account holder's name on statement.","4. Please ensure image uploaded is clear and readable."]
            },
        ],
    },
    errorTest : {
        invalidPan: 'Invalid PAN number. ',
        invalideDateFormat: 'Invalid Date format. ',
        invalidAge: 'You should be of 18 years of age'
    }  
}