export const LEADERBOARD_EVENT_NAMES = {
    LEADERBOARD_SCHEDULE: 'lb_schedule_event',
    LEADERBOARD_GROUP_CANCEL: 'lb_cancel_event',
    LEADERBOARD_CHILD_CANCEL: 'child_lb_cancel_event',
    LEADERBOARD_CHILD_STARTED: 'child_lb_start_event',
    LEADERBOARD_USER_SCORE_UPDATE: 'lb_user_score_event',
    LEADERBOARD_GROUP_COMPLETION: 'lb_campaign_completed'
}


export const LEADERBOARD_CAMPAIGN_STATUS = {
    UPCOMING : 5,
    ONGOING : 10,
    COMPLETED : 15,
    CANCELLED : 20,
}

export const LEADERBOARD_CAMPAIGN_STATUS_STRING = {
    UPCOMING : "UPCOMING",
    ONGOING : "ONGOING",
    COMPLETED : "COMPLETED",
    CANCELLED : "CANCELLED",
}


export const LEADERBOARD_STATUS = {
    ONGOING: "ONGOING",
    PARTICIPATED: "PARTICIPATED",
    COMPLETED: "COMPLETED",
    UPCOMING: "UPCOMING",
    CANCELLED: "CANCELLED"
}


export const LEADERBOARD_STATUS_STRING = {
    ONGOING: "Ongoing",
    PARTICIPATED: "Participated",
    COMPLETED: "Completed",
    UPCOMING: "Upcoming",
    CANCELLED: "Cancelled"
}

export const LEADERBOARD_STATUS_STRING_MAPPING = {
    [LEADERBOARD_STATUS.ONGOING]: "Ongoing",
    [LEADERBOARD_STATUS.PARTICIPATED]: "Participated",
    [LEADERBOARD_STATUS.COMPLETED]: "Completed",
    [LEADERBOARD_STATUS.UPCOMING]: "Upcoming",
    [LEADERBOARD_STATUS.CANCELLED]: "Cancelled"
}

export const LEADERBOARD_GROUP_TENET_STATUS = {
    RUNNING: "RUNNING",
    UPCOMING: "UPCOMING",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
    PARTIALLY_COMPLETED: "PARTIALLY_COMPLETED",
    PARTIALLY_CANCELLED: "PARTIALLY_CANCELLED"
}

export const DEFAULT_LEADERBOARD_PRIZE_CURRENCY_IDENTIFIER = 'DISCOUNT_CREDIT_SEGMENT'

export const LEADERBOARD_SORTING_ORDER = ["Participated", "Ongoing", "Upcoming", "Completed"]