export enum GsCommand {
    reserveRoom = 'reserve_room',
    roomTables = 'get_room_tables',
    tableDetails = 'get_ct_status',
    getRoomList = 'get_rooms',
    sitAtTable = 'sit_at_table',
    topup = 'top_up',
    topupValue = 'request_top_up_values',
    rebuy = 're_buy',
    iAmBack = 'i_am_back',
    leaveTableRequest = 'leave_table_request',
    unreserveTable = 'un_reserve_table',
    tournamentBlindStructure = 'get_blind_structure',
    tournamentStats = 'get_state',
    playerTournamentRegistration = 'register_tournament_player',
    playerTournamentUnregistration = 'unregister_tournament_player',
    playerTournamentStatus = 'get_player_current_state',
    playerMTTList = 'get_mtt_opened_list',
    playerMTTViewList = 'get_mtt_view_list',
    mttList = 'get_mtt',
    onlineUsersCount = "get_live_users",
    featuredMtt = "get_featured_mtt",
    tournamentEntryDetails = 'get_tournament_registration_info',
    recommendedRooms = 'get_recommended_games'
}