enum EventNames {
    USER_LOGOUT_SUCCESS="UserLogoutSuccess",
    USER_LOCATION_BLOCKED_BY_IP="UserLocationBlockedByIp",
    USER_LOCATION_UPDATE="UserLocationUpdate",
    USER_FEEDBACK="UserFeedback",
    USER_PAYOUT_SUCCESS="UserPayoutSuccess",
    USER_PAYOUT_FAILED="UserPayoutFailed",
    USER_PAYOUT_INITIATED="UserPayoutInitiated",
    USER_REFUND_INITIATED="UserRefundInitiated",
    USER_REFUND_COMPLETED="UserRefundCompleted",
    USER_REFUND_FAILURE="UserRefundFailure",
    USER_REVERT_REFUND_FAILURE="UserRevertRefundFailure",
    USER_KYC_COMPLETE="UserKycComplete",
    USER_KYC_FAILURE="UserKycFailure",
    USER_KYC_EXTRACT_FAILURE="UserKycExtractFailure",
    USER_KYC_EXTRACT_SUCCESS="UserKycExtractSuccess",
    USER_KYC_UPLOAD_SUCCESS="UserKycUploadSuccess",
    USER_KYC_PAN_SUCCESS="UserKycPanSuccess",
    USER_KYC_BANK_SUCCESS="UserKycBankSuccess",
    USER_DEPOSIT_SUCCESS="UserDepositSuccess",
    USER_FIRST_DEPOSIT_SUCCESS="UserFirstDepositSuccess",
    USER_DEPOSIT_FAILURE="UserDepositFailure",
    SERVICE_DEPOSIT_FAILURE="ServiceDepositFailure",
    USER_INSTALLED_PACKAGES="UserInstalledPackages",
    USER_SIGNUP_SUCCESS="UserSignupSuccess",
    USER_VERIFY_EMAIL="UserVerifyEmail",
    USER_BANK_STATUS ="UserBankStatus",
    USER_UPI_STATUS="UserUpiStatus",
    PRACTICE_APP_DOWNLOAD_SMS="PracticeAppDownloadSms",
    USER_PROPERTIES_UPDATE="UserPropertiesUpdate",
    LEADERBOARD_USER_SETTLEMENT="LeaderboardUserSettlement",
    LEADERBOARD_FRAUD_USER_SETTLEMENT="LeaderboardFraudUserSettlement",
    LEADERBOARD_RAKEBACK_USER_SETTLEMENT="LeaderboardRakeBackUserSettlement",
    AUTO_TOP_UP_SETTING_UPDATE= "AutoTopUpSettingUpdate",
    USER_REWARD_ALLOCATED="userRewardAllocated",
    USER_PROMO_BENEFIT_CREDITED="userPromoBenefitCredited",
    USER_KYC_PENDING="UserKycPending",
    USER_LEADERBOARD_SCORE_UPDATED='UserLeaderboardScoreUpdated',
    LEADERBOARD_GROUP_CREATED='LEADERBOARD_GROUP_CREATED',
    LEADERBOARD_CHILD_CREATED='LEADERBOARD_CHILD_CREATED',
    LEADERBOARD_GROUP_UPDATED='LEADERBOARD_GROUP_UPDATED',
    LEADERBOARD_CHILD_UPDATED='LEADERBOARD_CHILD_UPDATED',
    LEADERBOARD_PRIZE_POOL_CREATED='LEADERBOARD_PRIZE_POOL_CREATED',
    CHILD_LEADERBOARD_STARTED='CHILD_LEADERBOARD_STARTED',
}

export default EventNames;
